# Generated by Django 5.0.3 on 2024-07-03 15:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='judge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='folders_visible', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='folder',
            name='lawyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders_in_charge', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='folder',
            name='parent1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders_as_parent1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='folder',
            name='parent2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders_as_parent2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentcategory',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_categories', to='Payments.categorytype'),
        ),
        migrations.AddField(
            model_name='paymentdocument',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='Payments.paymentcategory'),
        ),
        migrations.AddField(
            model_name='paymentdocument',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_documents', to='Payments.folder'),
        ),
        migrations.AddField(
            model_name='paymentdocument',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
