# Generated by Django 5.0.3 on 2024-07-30 18:25

from django.db import migrations, models
import django.db.models.deletion
import uuid
from django.conf import settings

def get_case_model():
    return 'payments.Case'

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvocatCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('avocat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_parents', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(get_case_model(), on_delete=django.db.models.deletion.CASCADE, related_name='assigned_lawyers')),
            ],
            options={
                'unique_together': {('avocat', 'case')},
            },
        ),
        migrations.CreateModel(
            name='JugeCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('juge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_parents_judge', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(get_case_model(), on_delete=django.db.models.deletion.CASCADE, related_name='assigned_judges')),
            ],
            options={
                'unique_together': {('juge', 'case')},
            },
        ),
    ]
